---
title: "Flux based analysis test"
author: "Nhi Hin"
date: "2020-05-26"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r engine="bash"}
module load Python/3.7.0-foss-2016b
python
```

```{r engine="python"}
data_dir="/fast/users/a1669135/old"
zeb_model=cobra.io.read_sbml_model(join(data_dir, "Supp_Data.xml"))
```

```{r engine="text"}
urn:miriam:kegg.compound:C00001 does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id
urn:miriam:chemspider:937 does not conform to 'http(s)://identifiers.org/collection/id' or'http(s)://identifiers.org/COLLECTION:id
Traceback (most recent call last):
  File "/home/a1669135/.local/lib/python3.7/site-packages/cobra/io/sbml.py", line 255, in read_sbml_model
    **kwargs)
  File "/home/a1669135/.local/lib/python3.7/site-packages/cobra/io/sbml.py", line 471, in _sbml_to_model
    cobra_model.add_metabolites(metabolites)
  File "/home/a1669135/.local/lib/python3.7/site-packages/cobra/core/model.py", line 445, in add_metabolites
    self.metabolites += metabolite_list
  File "/home/a1669135/.local/lib/python3.7/site-packages/cobra/core/dictlist.py", line 272, in __iadd__
    self.extend(other)
  File "/home/a1669135/.local/lib/python3.7/site-packages/cobra/core/dictlist.py", line 199, in extend
    "Is it present twice?" % (str(the_id), i))
ValueError: id 'acoa_c' at index 2808 is non-unique. Is it present twice?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a1669135/.local/lib/python3.7/site-packages/cobra/io/sbml.py", line 268, in read_sbml_model
    raise_from(cobra_error, original_error)
  File "<string>", line 3, in raise_from
cobra.io.sbml.CobraSBMLError: Something went wrong reading the SBML model. Most likely the SBML model is not valid. Please check that your model is valid using the `cobra.io.sbml.validate_sbml_model` function or via the online validator at http://sbml.org/validator .
	`(model, errors) = validate_sbml_model(filename)`
If the model is valid and cannot be read please open an issue at https://github.com/opencobra/cobrapy/issues .
```

